apiVersion: v1
kind: Pod

metadata:
  name: multicontainer

spec:
 containers:
  - name: nginx
    image: nginx
  - name: alma
    image: "almalinux:9"
    command: 
      - sleep
      - "3000"