apiVersion: v1
kind: Service

metadata:
  name: nginx-service

spec:
  selector:
     name: service-test
     environment: dev
     project: localhelp
     component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80