apiVersion: v1
kind: Service

metadata:
  name: nginx-service-lb

spec:
  type: LoadBalancer
  selector:
     name: service-test
     environment: dev
     project: localhelp
     component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31100