apiVersion: v1
kind: Pod

metadata:
  name: annotations
  labels:
    course: k8
    learning: self
  annotations:
    kubernetes.io/created-by: 'bunny'
    jenkins.build.url: 'https://jenkins.localhelp.store/job/backend/32'
spec:
  containers:
    - name: nginx
      image: nginx