apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: localhelp
  region: us-east-1

managedNodeGroups:
  - name: localhelp
    instanceType: t3.medium
    desiredCapacity: 2
    spot: true